# Generated by Django 5.0.1 on 2024-01-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=100)),
                ('published_date', models.DateField(null=True)),
                ('category', models.CharField(max_length=150)),
                ('distribution_expense', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
